# .github/workflows/automerge.yml  (in each TARGET repo)
name: automerge
on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automerge"
          MERGE_FILTER_AUTHOR: "Greg-T8"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          # Keep PRs updated if branch protection requires up-to-date base
          UPDATE_LABELS: "automerge"
          UPDATE_METHOD: "rebase"
          MERGE_DELETE_BRANCH: "true"
